spring:
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao
    password: 030508
    username: root
  session:
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

